# Generated by Django 5.0.6 on 2024-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_lastblogs_formatted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastblogs',
            name='formatted_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
